### PR TITLE
Added Signin Signup Header Footer Tailwindcss , Kindly Approve PR

### LINKED ISSUE #3: Adding Features
Hi @sunny7899 , Please let me know what are the features can I work on this project Please assign the task to me add label hacktoberfest, thanks

### PR DESCRIPTION
**Pull request by HMSagar2701**
image
image
image
Please check this, Thanks !!!

### CODE REVIEW

**Comment by sunny7899** [comment]
@HMSagar2701  Can you please resolve the conflicts. Also dont remove the code add new page. The code you removed in that we have used some tags.

**Comment by HMSagar2701** [comment]
> @HMSagar2701 Can you please resolve the conflicts. Also dont remove the code add new page. The code you removed in that we have used some tags
Okay Sorry for that, I will work on resolving conflict.

**Comment by HMSagar2701** [comment]
Hi @sunny7899, Commented code which is present in **index.js**  needs to be there as it is right ?

**Comment by HMSagar2701** [comment]
hi @sunny7899 , Please check Merge conflict is resolved in latest commit

**Comment by sunny7899** [comment]
@HMSagar2701 yes pls keep those index.js  changes as it is

**Comment by HMSagar2701** [comment]
Done that in index.js, Please check, let me know if i need to change any other things, thanks

**Pull request merged**
