### PR TITLE
Calories Deficit Calculator

### LINKED ISSUE #16: Calories deficit calculator
Create a simple calorie deficit calculator that calculates the suitable amount of calories a user should consume.

### PR DESCRIPTION
**Pull request by aetherfaye1009**
### What you get : 
- Calculator Total Daily Energy Expenditure (TDEE) based on user input.
- Implemented Body Mass Index (BMI) calculation and categorization.

### User Experience Enhancements:
- Implemented input validation for numeric fields to ensure only valid entries.
- Utilized Sweet Alert 2 for a user-friendly and visually appealing display of results.

### Code Quality Improvements:
- Ensured code follows best practices for maintainability and readability.
- Added comments and documentation where necessary for clarity.

### Testing:
- Conducted manual testing to verify the accuracy of calculations and the functionality of the user interface.
Ensured that all new features work seamlessly with existing code.

### Reference:
- https://asean-endocrinejournal.org/index.php/JAFES/article/view/477/975
- https://www.medicinenet.com/how_to_calculate_calorie_deficit_for_weight_loss/article.htm
- https://sweetalert2.github.io/

P.S. `npm install` is required  after merge.  UI is based on the Sign In form. I just reuse it.

Issues: #16

Let me know if there is anything you want me to add.

### CODE REVIEW

**Comment by aetherfaye1009** [comment]
image
image
image

**Comment by aetherfaye1009** [comment]
`package-lock.json` conflicts could be because I installed the "Sweet Alert 2".

**Comment by sunny7899** [comment]
@aetherfaye1009  please resolve the conflict

**Comment by aetherfaye1009** [comment]
@sunny7899 done, please review again.

**Pull request merged**
